export const SIGN_UP_START= 'SIGN_UP_START'
export const SIGN_UP_SUCCESS= 'SIGN_AP_SUCCESS'
export const SIGN_UP_FAILED= 'SIGN_UP_FAILED'

export const LOGIN_START= 'LOGIN_START'
export const LOGIN_SUCCESS='LOGIN_SUCCESS'
export const LOGIN_FAILED='LOGIN_FAILED'

export const DARK_LIGHT='DARK_LIGHT'

export const QR_CODE_START='QR_CODE_START'
export const QR_CODE_SUCCESS='QR_CODE_SUCCESS'
export const QR_CODE_FAILED='QR_CODE_FAILED'

export const LOGOUT_START='LOGOUT_START'
export const LOGOUT_SUCCESS='LOGOUT_SUCCESS'
export const LOGOUT_FAILED='LOGOUT_FAILED'

export const OTP_START='OTP_START'
export const OTP_SUCCESS='OTP_SUCCESS'
export const OTP_FAILED='OTP_FAILED'

export const CLEAN_UP='CLEAN_UP'

export const TWO_FA_START='TWO_FA_START'
export const TWO_FA_SUCCESS='TWO_FA_SUCCESS'
export const TWO_FA_FAILED='TWO_FA_FAILED'

export const SEND_VERIFY_START='SEND_VERIFY_START'
export const SEND_VERIFY_SUCCESS='SEND_VERIFY_SUCCESS'
export const SEND_VERIFY_FAILED='SEND_VERIFY_FAILED'

export const TWOFA_LOGIN_START='TWOFA_LOGIN_START'
export const TWOFA_LOGIN_SUCCESS='TWOFA_LOGIN_SUCCESS'
export const TWOFA_LOGIN_FAILED='TWOFA_LOGIN_FAILED'

export const SEND_VALIDATE_START='SEND_VALIDATE_START'
export const SEND_VALIDATE_SUCCESS='SEND_VALIDATE_SUCCESS'
export const SEND_VALIDATE_FAILED='SEND_VALIDATE_FAILED'

export const AUTO_AUTH='AUTO_AUTH'

export const GET_ACCESS_BY_REFRESH='GET_ACCESS_BY_REFRESH'

export const FETCH_USER_START='FETCH_USER_START'
export const FETCH_USER_SUCCESS='FETCH_USER_SUCCESS'
export const FETCH_USER_FAILED='FETCH_USER_FAILED'

export const POST_USER_START='POST_USER_START'
export const POST_USER_SUCCESS='POST_USER_SUCCESS'
export const POST_USER_FAILED='POST_USER_FAILED'

export const INIT_USER='INIT_USER'

export const FETCH_BANK_START="FETCH_BANK_START"
export const FETCH_BANK_SUCCESS="FETCH_BANK_SUCCESS"
export const FETCH_BANK_FAILED="FETCH_BANK_FAILED"




